UImate/urls.py
from django.contrib import admin
from django.urls import include, path
from tukerjakun.views import get_formulir, get_hasil_formulir

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sso_ui.urls')),
    path('jakun/', include('tukerjakun.urls')),
    path('kenalan/', include('kenalan.urls')),
    path('passing/', include('PassingBarang.urls'), name= 'PassingBarang')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kirim_pesan/', views.kirim_pesan, name='kirim_pesan')
]

tukerjakun/urls.py
from django.urls import path

from . import views

app_name = 'tukerjakun'
urlpatterns = [
    path('', views.get_formulir, name='index'),
    path('formulir/', views.get_formulir, name='tuker'),
    path('get_hasil_formulir/', views.get_hasil_formulir, name='tukerjakun'),
]

tukerjakun/models.py
from django.db import models

# Create your models here.
class Tukaran(models.Model):
    nama = models.CharField(max_length=100)
    makara = models.CharField(max_length=100)
    ukuran = models.CharField(max_length=100)
    kontak = models.CharField(max_length=100)

tukerjakun/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Tukaran

# Create your views here.
def get_formulir(request):
    response ={}
    return render(request,'formulir.html', response)

def get_hasil_formulir(request):
    if request.method == 'POST':
        Tukaran.objects.create(nama=request.POST['nama'], makara=request.POST['makara'], ukuran=request.POST['ukuran'], kontak=request.POST['kontak'])
    jakun =Tukaran.objects.all()
    response ={'jakun':jakun}
    return render(request,'tukerjakun.html', response)

tukerjakun/templates/formulir.html
{% extends 'base.html' %}
{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}

{% block content %}

<style>
  input[type=text],
  select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: orange;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: yellow;
    color: black;
    transition: 0.5s;
  }
</style>

<section class="section-container d-flex flex-column align-items-center text-center">
  <h1 class="animate__animated animate__tada semi-bold-font pt-4 text-center">Mau Tuker Jakun Kamu?</h1>
  <form class="card custom-card large-card" action="{% url 'tukerjakun:tukerjakun' %}" method="POST"> {% csrf_token %}
    <label>Nama</label>
    <input type="text" name="nama" placeholder="Nama kamu...">
    <label>Fakultas</label>
    <select id="makara" name="makara">
      <option value="🟢 Fakultas Kedokteran">🟢 Fakultas Kedokteran</option>
      <option value="🟢⚪ Fakultas Kedokteran Gigi">🟢⚪ Fakultas Kedokteran Gigi</option>
      <option value="🔵⚫ Fakultas Matematika dan Ilmu Pengetahuan Alam">🔵⚫ Fakultas Matematika dan Ilmu Pengetahuan Alam</option>
      <option value="🔵 Fakultas Teknik">🔵 Fakultas Teknik</option>
      <option value="🔴 Fakultas Hukum">🔴 Fakultas Hukum</option>
      <option value="⚫ Fakultas Ekonomi dan Bisnis">⚫ Fakultas Ekonomi dan Bisnis</option>
      <option value="⚪ Fakultas Ilmu Pengetahuan Budaya">⚪ Fakultas Ilmu Pengetahuan Budaya</option>
      <option value="🔵 Fakultas Psikologi">🔵 Fakultas Psikologi</option>
      <option value="🟠 Fakultas Ilmu Sosial dan Ilmu Politik">🟠 Fakultas Ilmu Sosial dan Ilmu Politik</option>
      <option value="🔴🟣 Fakultas Ilmu Administrasi">🔴🟣 Fakultas Ilmu Administrasi</option>
      <option value="🟣 Fakultas Kesehatan Masyarakat">🟣 Fakultas Kesehatan Masyarakat</option>
      <option value="🔵🔴 Fakultas Ilmu Komputer">🔵🔴 Fakultas Ilmu Komputer</option>
      <option value="🔵🔵🔵 Fakultas Ilmu Keperawatan">🔵🔵🔵 Fakultas Ilmu Keperawatan</option>
      <option value="🔵🟢 Fakultas Farmasi">🔵🟢 Fakultas Farmasi</option>
      <option value="🟢🟠🔵 Program Vokasi (DIII)">🟢🟠🔵 Program Vokasi (DIII)</option>
      <option value="⚫🟢 Sekolah Ilmu Lingkungan">⚫🟢 Sekolah Ilmu Lingkungan</option>
      <option value="⚫⚫ Sekolah Kajian Stratejik dan Global">⚫⚫ Sekolah Kajian Stratejik dan Global</option>
    </select>
    <label>Ukuran</label>
    <select id="ukuran" name="ukuran">
      <option value="XXXS">XXXS</option>
      <option value="XXS">XXS</option>
      <option value="XS">XS</option>
      <option value="S">S</option>
      <option value="M">M</option>
      <option value="L">L</option>
      <option value="XL">XL</option>
      <option value="XXL">XXL</option>
      <option value="XXXL">XXXL</option>
    </select>
    <label>Kontak</label>
    <input type="text" name="kontak" placeholder="Kontak yang dapat dihubungi...">
    <input type="submit" value="Submit">
  </form>
</section>
{% endblock content %}

tukerjakun/templates/tukerjakun.html
{% extends 'base.html' %}
{% load static %}

{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
    crossorigin="anonymous" />
{% endblock %}

{% block content %}
<style>
    .myDiv {
        border: 5px outset black;
        background-color: yellow;
        text-align: center;
    }
</style>

<section class="section-container d-flex flex-column align-items-center text-center">
    <h1 class="animate__animated animate__tada semi-bold-font pt-4 text-center">Liat - Liat Jakun</h1>
    <a class="card custom-card zoom small-card link-unstyled" href="{% url 'tukerjakun:tuker' %}">
        <h2 class="m-0">
            <center>
                Tambahin Jakun
            </center>

        </h2>
    </a>
    <div class="m-4 mb-5 card-columns">
        {%for jaket in jakun%}
        <div class="card custom-card link-unstyled rainbow-card align-items-center inlinedis">
            <h3 class="m-0 text-center">
                👑 Milik <strong style="color:var(--main-black)">{{jaket.nama}}</strong> <br>
                🏛️ Makara <strong style="color:var(--main-black)">{{jaket.makara}}</strong> <br>
                🥼 Ukuran <strong style="color:var(--main-black)">{{jaket.ukuran}}</strong> <br>
                ☎️ Kontak <strong style="color:var(--main-black)">{{jaket.kontak}}</strong> <br>
            </h3>
        </div>
        {%endfor%}
    </div>
</section>
{% endblock %}

{% block userscript %}
<script src="{% static 'scripts/rainbowcard.js' %}"></script>
<script src="{% static 'scripts/imageerror.js' %}"></script>
{% endblock userscript %}