UImate/urls.py
from django.contrib import admin
from django.urls import include, path
from tukerjakun.views import get_formulir, get_hasil_formulir

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sso_ui.urls')),
    path('jakun/', include('tukerjakun.urls')),
    path('kenalan/', include('kenalan.urls')),
    path('passing/', include('PassingBarang.urls'), name= 'PassingBarang')
]

kenalan/urls.py
"""SSO UI urls module."""
from django.urls import path

from . import views

app_name = 'kenalan'
urlpatterns = [
    path('', views.index, name='index'),
    path('pertemuan/', views.daftar_pertemuan, name='daftar_pertemuan'),
    path('tambah/', views.tambah_pertemuan, name='tambah_pertemuan'),
    path('toggle_hadir/', views.toggle_hadir, name='toggle_hadir'),
    path('hapus/<int:id>/', views.hapus_pertemuan, name='hapus_pertemuan'),
    path('detail/<int:id>/', views.detail_pertemuan, name='detail_pertemuan'),
    path('komentar/<int:id>/', views.tambah_komentar, name='tambah_komentar'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kirim_pesan/', views.kirim_pesan, name='kirim_pesan')
]

kenalan/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from sso_ui.models import Profile
from django.db import models

from datetime import datetime, timedelta

def get_str_time(menit):
    jam = menit//60
    menit -= jam*60
    ret = (f'{jam} Jam' if jam > 0 else '')
    if(jam > 0 and menit > 0): ret += ' '
    ret += (f'{menit} Menit' if menit > 0 else '')
    return ret

class Pertemuan(models.Model):
    nama = models.CharField(max_length=30, default = "Pertemuan asyik!")
    pembuat = models.ForeignKey(Profile, related_name="pembuat", on_delete=models.CASCADE)
    peserta = models.ManyToManyField(Profile, related_name="peserta")
    waktu_mulai = models.DateTimeField()
    durasi = models.CharField(max_length=30, choices=[(get_str_time(x), get_str_time(x)) for x in [5, 10, 15, 30, 45, 60, 90, 120, 150, 180, 210, 240]], default = '1 Jam')
    kapasitas = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(40)], default = 10)
    gambar = models.URLField(default="https://static.wikia.nocookie.net/gensin-impact/images/c/cf/Character_Venti_Portrait.png/revision/latest/scale-to-width-down/1000?cb=20200916184309")

    def __str__(self):
        return self.nama
    class Meta:
        ordering = ["waktu_mulai"]

class Komentar(models.Model):
    konten = models.TextField()
    waktu = models.DateTimeField(auto_now_add=True, blank=True)
    pertemuan = models.ForeignKey(Pertemuan, related_name="komentar", on_delete=models.CASCADE)
    penulis = models.ForeignKey(Profile, related_name="penulis", on_delete=models.CASCADE)
    def __str__(self):
        return self.konten
    class Meta:
        ordering = ["waktu"]
    

kenalan/forms.py
from django.forms import ModelForm, DateTimeInput, CheckboxInput, Textarea
from .models import *

class PertemuanForm(ModelForm):
    class Meta:
        model = Pertemuan
        
        fields = '__all__'
        labels = {
            'nama': 'Nama Pertemuan',
            'waktu_mulai': 'Waktu Mulai'
        }
        widgets = {
            'waktu_mulai': DateTimeInput(attrs={'class': 'datetimepicker'})
        }

class KomentarForm(ModelForm):
    class Meta:
        labels = {
            'konten' : 'Diskusi'
        }
        model = Komentar
        fields = '__all__'
        widgets = {
            'konten': Textarea(attrs={'rows': 3, 'cols': 50}),
        }

kenalan/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib import messages
from django.http import Http404
from .models import *
from .forms import *
import copy, random
from django.utils import timezone
colors = ["red", "orange", "yellow", "green", "blue", "purple", "violet"]

original = {
    "description" : "Kenalan, Yuk!",
    "title" : "Kenalan, Yuk!",
    "need_login" : False
}

def get_hour(deltaHour):
    now = timezone.now()
    # Rounds to nearest hour by adding a timedelta hour if minute >= 30
    return (now.replace(second=0, microsecond=0, minute=0, hour=now.hour)
               +timedelta(hours=(now.minute//30)+deltaHour))

def get_random_title():
    title = ["Pertemuan seru!", "Main game bareng!", "Cari token!", "Ayo belajar matdas!", "Ayo main Genshin!", "Dota Yuk!!!"]
    return random.choice(title)

def index(request):
    context = copy.copy(original)
    return render(request, "kenalan.html", context)

def daftar_pertemuan(request):
    context = copy.copy(original)
    context["description"] = "Lihat-lihat ada pertemuan apa aja"
    context["title"] = "Daftar Pertemuan"
    context["pertemuans"] = Pertemuan.objects.all()
    return render(request, "daftar_pertemuan.html", context)

def tambah_pertemuan(request):
    context = copy.copy(original)
    context["description"] = "Tambahkan pertemuan baru di sini"
    context["title"] = "Tambah Pertemuan"
    context["need_login"] = True
    request.POST._mutable = True
    if(request.POST): form = PertemuanForm(request.POST)
    else: form = PertemuanForm(initial={'waktu_mulai': get_hour(1), 'nama':get_random_title()})

    if(not request.user.is_authenticated):
        messages.warning(request, "Login dulu untuk bisa menambahkan pertemuan!")
        if(request.method == "POST"): return redirect('kenalan:tambah_pertemuan')
    else:
        form.data["pembuat"] = request.user.id
        form.data["peserta"] = request.user.id
        
    if(form.is_valid() and request.method == "POST"):
        nama = form.cleaned_data['nama']
        messages.success(request, f'Berhasil menambahkan pertemuan {nama}')
        form.save()
        return redirect('kenalan:daftar_pertemuan')

    context["form"] = form
    return render(request, "tambah_pertemuan.html", context)

    
def hapus_pertemuan(request, id):
    if(request.method != "POST"):
        return redirect('kenalan:daftar_pertemuan')
    
    context = copy.copy(original)
    pertemuan = get_object_or_404(Pertemuan, id=id)

    if(str(pertemuan.pembuat.id) != str(request.POST["pembuat"])):
        raise Http404("Non-maker attempt to delete meeting")

    if request.method == 'POST':
        messages.success(request, f'{pertemuan} berhasil dihapus')
        pertemuan.delete()
    
    return redirect('kenalan:daftar_pertemuan')

def detail_pertemuan(request, id):
    context = copy.copy(original)
    all_pertemuan = Pertemuan.objects.all()
    for i in range(len(all_pertemuan)):
        if(all_pertemuan[i].id == id):
            context["pertemuan"] = all_pertemuan[i]
            context["next_pertemuan"] = all_pertemuan[i+1 if i+1 < len(all_pertemuan) else 0].id
            context["prev_pertemuan"] = all_pertemuan[i-1 if i > 0 else len(all_pertemuan)-1].id
            break

    if("pertemuan" not in context): raise Http404("Pertemuan tidak ditemukan!")

    context["title"] = f'{context["pertemuan"].nama}'
    context["description"] = f'Detail pertemuan {context["pertemuan"].nama}'
    context["all_peserta"] = context["pertemuan"].peserta.all()
    context["kapasitas"] = f'{len(context["all_peserta"])}/{context["pertemuan"].kapasitas}'
    context["komentars"] = context["pertemuan"].komentar.all()
    
    if(len(context["all_peserta"]) == 0):
        context["all_peserta"] = ["Hah? Kosong! 🐴"]

    if(request.user.is_authenticated):
        context["full_name"] = Profile.objects.get(id=request.user.id)
        context["cant_register"] = (context["full_name"] in context["all_peserta"])
    
    
    context["komentar_form"] = KomentarForm(request.POST or None)
    return render(request, "detail_pertemuan.html", context)

def toggle_hadir(request):
    if(request.method != "POST"):
        return redirect("kenalan:daftar_pertemuan")
    data = request.POST
    pertemuan = get_object_or_404(Pertemuan, id=data['pertemuan'])
    peserta = get_object_or_404(Profile, id=data['peserta'])
    if(peserta in pertemuan.peserta.all()):
        pertemuan.peserta.remove(peserta)
        messages.info(request, f'Kamu tidak jadi hadir di pertemuan ini!') 
    else:
        if(len(pertemuan.peserta.all()) >= pertemuan.kapasitas):
            messages.error(request, f'Belum bisa menambahkan karena kapasitasnya penuh 😔')
        else:
            pertemuan.peserta.add(peserta)
            messages.success(request, f'Kamu akan hadir di pertemuan ini!') 
    return redirect("kenalan:detail_pertemuan", id=data['pertemuan'])

def tambah_komentar(request, id):
    if not request.user.is_authenticated:
        return redirect('sso_ui:login')
    if(request.method == "POST"):
        request.POST._mutable = True
        komentarForm = KomentarForm(request.POST)
        komentarForm.data["penulis"] = request.user.id
        komentarForm.data["pertemuan"] = id
        if(komentarForm.is_valid()):
            messages.success(request, "Komentar berhasil ditambahkan")
            komentarForm.save()
    return redirect("kenalan:detail_pertemuan", id=id)

kenalan/templates/daftar_pertemuan.html
{% extends 'base.html' %}

{% load static %}

{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}

{% block content %}
<section class="section-container d-flex flex-column align-items-center text-center">
    
    <h1 class="animate__animated animate__tada semi-bold-font pt-4">Liat-Liat Pertemuan</h1>

    {% include 'messages.html' %}
    
    {% for pertemuan in pertemuans %}
        <a class="card custom-card zoom small-card link-unstyled rainbow-card m-3" href="{% url 'kenalan:detail_pertemuan' id=pertemuan.id%}">
            <h2 style="font-weight: 700;">
                📢 {{ pertemuan }}
            </h2>
            
            <h3 class="m-0">
                👑 oleh {{ pertemuan.pembuat|default:" " }}  <br>
                📆 {{ pertemuan.waktu_mulai|date:'l, d E Y' }} <br>
                ⏰ Pukul {{ pertemuan.waktu_mulai|date:'H:i' }} <br>
                ⏲️ {{ pertemuan.durasi }}
            </h3>
        </a>
    {% endfor %}
    
    
</section>

{% endblock content %}

{% block userscript %}
<script src="{% static 'scripts/rainbowcard.js' %}"></script>
{% endblock userscript %}

kenalan/templates/detail_pertemuan.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}

{% block style %}
    <link href="{% static 'css/komentar.css' %}" rel="stylesheet" type="text/css"></link>
{% endblock style %}

{% block content %}
<section class="section-container d-flex flex-column dark-color align-items-center">
    <h1 class="animate__animated animate__pulse semi-bold-font pt-4 text-center">Meski Pandemi <br> Masih Bisa Nongki</h1>

    {% include 'messages.html' %}

    <div class="card custom-card small-card d-flex align-items-center justify-content-between dark-text">
        <!-- {{user.is_authenticated}} -->
        <!-- {{full_name}} -->
        <div class="d-flex flex-row justify-content-around m-2 light-text" style="width: 95%;">
            <a class="btn btn-primary" href="{% url 'kenalan:detail_pertemuan' id=prev_pertemuan %}">
                <i class="far fa-hand-point-left"></i> Prev
            </a>
            <a class="btn btn-secondary" href="{% url 'kenalan:daftar_pertemuan' %}">
                Kembali
            </a>
            <a class="btn btn-primary" href="{% url 'kenalan:detail_pertemuan' id=next_pertemuan %}">
                Next <i class="far fa-hand-point-right"></i>
            </a>
        </div>

        <h2 style="font-weight: 700;"> 📢 {{ pertemuan }}</h2>

        {% if user.is_authenticated %}
        <div class="d-flex flex-row justify-content-center m-2 light-text" style="width: 95%;">
            <form class="mr-2" action="{% url 'kenalan:toggle_hadir' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="pertemuan" value={{pertemuan.id}}>
                <input type="hidden" name="peserta" value={{user.id}}>
                {% if cant_register %}
                <button class="btn btn-danger" type="submit">
                    <i class="far fa-calendar-times"></i> Batal hadir
                </button>
                {% else %}
                <button class="btn btn-success" type="submit">
                    <i class="far fa-calendar-plus"></i> Hadir
                </button>
                {% endif %}
            </form>

            {% if user.id == pertemuan.pembuat.id %}
            <form class="ml-2" action="{% url 'kenalan:hapus_pertemuan' id=pertemuan.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="pembuat" value={{user.id}}>
                <button class="btn btn-danger" type="submit">
                    <i class="far fa-trash-alt"></i> Hapus
                </button>
            </form>
            {% endif %}

        </div>
        {% endif %}
        <h3 class="m-2 text-center">👥 : {{kapasitas}}</h3>
        <img id="img-preview" src="{{pertemuan.gambar}}" alt="Preview" class="card-img-top"
            style="width: 70%; max-height: 200px; object-fit: cover; object-position: 50% 0;">
        <label id="img-warning" style="display: none; color: var(--main-red);">Gambar tidak tersedia!</label>
        <h3 class="m-0 text-center">
            👑 oleh <strong style="color:var(--main-dark-blue)">{{ pertemuan.pembuat|default:" " }}</strong> <br>
            📆 {{ pertemuan.waktu_mulai|date:'l, d E Y' }} <br>
            ⏰ Pukul {{ pertemuan.waktu_mulai|date:'H:i' }} <br>
            ⏲️ {{ pertemuan.durasi }}
            <br> <br>
            <strong>Daftar Peserta:</strong> <br>
            {% for peserta in all_peserta %}
            {{peserta}} <br>
            {% endfor %}
        </h3>
        <hr>
            {% for komentar in komentars %}
            <div class="m-1 zoom comment comment-{% if komentar.penulis.id == user.id %}self{% else %}others{% endif %} {{komentar.penulis.color}}" style>
                <strong style="color: var(--main-dark-{{komentar.penulis.color}});">
                    {{komentar.penulis}}
                </strong>
                <div style="color: var(--main-black);">
                    {{komentar.konten}}
                </div>
            </div>
            {% endfor %}
        <form action="{% url 'kenalan:tambah_komentar' id=pertemuan.id %}" method="post">
            {% csrf_token %}
            {{ komentar_form.konten|as_crispy_field }}
            <button class="btn btn-success" type="submit">
                Submit <i class="fas fa-paper-plane"></i>
            </button>
        </form>
    </div>
</section>

{% endblock %}
{% block userscript %}
<script src="{% static 'scripts/imageerror.js' %}"></script>
{% endblock userscript %}

kenalan/templates/kenalan.html
{% extends 'base.html' %}

{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}

{% block content %}
<section class="section-container d-flex flex-column align-items-center text-center">
    
    <h1 class="animate__animated animate__tada semi-bold-font">Kenalan, Yuk!</h1>

    {% include 'messages.html' %}

    <a class="card custom-card zoom small-card link-unstyled" href="{% url 'kenalan:tambah_pertemuan' %}">
        <h2 class="m-0">
            Tambahin Meeting
        </h2>
    </a>
    
    <a class="card custom-card zoom small-card link-unstyled" href="{% url 'kenalan:daftar_pertemuan' %}">
        <h2 class="m-0">
            Liat Meeting
        </h2>
    </a>
    
</section>

{% endblock content %}

kenalan/templates/tambah_pertemuan.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}

{% block content %}
<section class="section-container d-flex flex-column dark-color align-items-center">
    <h1 class="animate__animated animate__pulse semi-bold-font pt-4">Buat Pertemuan</h1>

    {% include 'messages.html' %}

    <div class="card custom-card medium-card d-flex align-items-center justify-content-between">
        <form class="w-75 m-2" action="{% url 'kenalan:tambah_pertemuan' %}" method="post">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.nama|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.kapasitas|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.waktu_mulai|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.durasi|as_crispy_field }}
                </div>
            </div>
            
            <div class="d-flex flex-column justify-content-between">
                {{ form.gambar|as_crispy_field }}
                <div class="btn btn-info mb-2" id="preview-btn">Preview Gambar</div>
            </div>
            
            <label>Preview</label> <br>
            <img id="img-preview" src="https://static.wikia.nocookie.net/gensin-impact/images/c/cf/Character_Venti_Portrait.png/revision/latest/scale-to-width-down/1000?cb=20200916184309"
                alt="Gambar Pertemuan" class="card-img-top" style="margin: 0; margin-bottom: 1em; width: 70%; max-height: 200px; object-fit: cover; object-position: 50% 0;">
            <br>
            <label id="img-warning" style="display: none; color: var(--main-red);">Gambar tidak tersedia!</label>
            <button class="btn btn-success" type="submit" id="submit">Tambah <i class="fas fa-plus"></i></button>
            <a href="{% url 'kenalan:index' %}" class="btn btn-dark">Kembali <i class="far fa-hand-point-left"></i></a>
        </form>
    </div>
</section>

{% endblock %}
{% block userscript %}
{% include 'datepicker.html' %}
<script src="{% static 'scripts/imagepreview.js' %}"></script>
{% endblock userscript %}