PassingBarang/urls.py
from django.urls import path

from . import views

app_name = 'PassingBarang'
urlpatterns = [
    path('', views.list_barang, name='index'),
    path('detil/<int:id_number>/', views.detil, name='detil'),
    path('tambah/', views.tambah, name = 'tambah'),
    path('detil/confirm/<int:id_number>/', views.confirm, name='confirm'),
    path('status/<area>/', views.area_status, name = 'status'),
]

UImate/urls.py
from django.contrib import admin
from django.urls import include, path
from tukerjakun.views import get_formulir, get_hasil_formulir

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sso_ui.urls')),
    path('jakun/', include('tukerjakun.urls')),
    path('kenalan/', include('kenalan.urls')),
    path('passing/', include('PassingBarang.urls'), name= 'PassingBarang')
]

kenalan/urls.py
"""SSO UI urls module."""
from django.urls import path

from . import views

app_name = 'kenalan'
urlpatterns = [
    path('', views.index, name='index'),
    path('pertemuan/', views.daftar_pertemuan, name='daftar_pertemuan'),
    path('tambah/', views.tambah_pertemuan, name='tambah_pertemuan'),
    path('toggle_hadir/', views.toggle_hadir, name='toggle_hadir'),
    path('hapus/<int:id>/', views.hapus_pertemuan, name='hapus_pertemuan'),
    path('detail/<int:id>/', views.detail_pertemuan, name='detail_pertemuan'),
    path('komentar/<int:id>/', views.tambah_komentar, name='tambah_komentar'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kirim_pesan/', views.kirim_pesan, name='kirim_pesan')
]

sso_ui/urls.py
"""SSO UI urls module."""
from django.urls import path
from django_cas_ng import views as cas_views

from . import views

app_name = 'sso_ui'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', cas_views.LoginView.as_view(), name='login'),
    path('logout/', cas_views.LogoutView.as_view(), name='logout'),
]

tukerjakun/urls.py
from django.urls import path

from . import views

app_name = 'tukerjakun'
urlpatterns = [
    path('', views.get_formulir, name='index'),
    path('formulir/', views.get_formulir, name='tuker'),
    path('get_hasil_formulir/', views.get_hasil_formulir, name='tukerjakun'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' type='image/x-icon' %}">
  <meta charset="utf-8" />
  <meta name="keywords" content="UImate!" />
  <meta name="author" content="UImateDev" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="description" content="{{ description }}" />
  <title>{{ title }}</title>

  <!-- jQuery -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
    crossorigin="anonymous"></script>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
    crossorigin="anonymous" />

  {% block cdnscript %} {% endblock %}

  <!-- Styling -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/nav.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/footer.css' %}" rel="stylesheet" type="text/css" />
  {% block style %} {% endblock %}

</head>

<body>

  {% include "nav.html" %}

  {% block content %} {% endblock %}

  {% include "footer.html" %}
</body>

<script src="{% static 'scripts/scroll.js' %}"></script>
{% block userscript %} {% endblock %}

</html>

templates/datepicker.html
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
    integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw=="
    crossorigin="anonymous"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
    integrity="sha512-f0tzWhCwVFS3WeYaofoLWkTP62ObhewQ1EZn65oSYDZUg1+CyywGKkWzm8BxaJj5HGKI72PnMH9jYyIFz+GH7g=="
    crossorigin="anonymous" />
<script src="{% static 'scripts/datepicker.js' %}"></script>

templates/footer.html
{% load static %}

<footer class="footer-container d-flex flex-column align-items-center text-center">
  <p class="mt-4">Made with 💖 in Indonesia</p>
  <p >Copyright © UImate 2020.</p>  
  <p class="mb-4">All rights reserved.</p>  
</footer>

templates/messages.html
{% if messages %}
    <ul class="messages container mt-4 mb-0" style="list-style: none;">
        {% for message in messages %}
        {% if message.tags == "error" %} <li  class="alert alert-danger alert-dismissible fade show" >
        {% else %} <li  class="alert alert-{{ message.tags }} alert-dismissible fade show" >{% endif %}
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
        {% endfor %}
    </ul>
{% endif %}

templates/nav.html
<nav id="main-navbar" class="navbar navbar-expand-lg sticky-top {%if stickynav %}sticky{%endif%}">

  <a class= "navbar-brand nav-link" href="/">💛 UImate</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
      class="navbar-toggler-icon">
      <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="nav navbar-nav ml-auto navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home' %}"><strong>Beranda</strong></a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sso_ui:profile' %}"><strong>Profil</strong></a>
      </li>
      {% endif %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'kenalan:index' %}"><strong>Kenalan</strong></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'PassingBarang:index' %}"><strong>Waris Barang</strong></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'tukerjakun:tukerjakun' %}"><strong>Tukar Jakun</strong></a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sso_ui:logout' %}"><strong>Log out</strong></a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sso_ui:login' %}"><strong>Log in</strong></a>
      </li>
      {% endif %}
    </ul>


  </div>

</nav>