PassingBarang/urls.py
from django.urls import path

from . import views

app_name = 'PassingBarang'
urlpatterns = [
    path('', views.list_barang, name='index'),
    path('detil/<int:id_number>/', views.detil, name='detil'),
    path('tambah/', views.tambah, name = 'tambah'),
    path('detil/confirm/<int:id_number>/', views.confirm, name='confirm'),
    path('status/<area>/', views.area_status, name = 'status'),
]

UImate/urls.py
from django.contrib import admin
from django.urls import include, path
from tukerjakun.views import get_formulir, get_hasil_formulir

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sso_ui.urls')),
    path('jakun/', include('tukerjakun.urls')),
    path('kenalan/', include('kenalan.urls')),
    path('passing/', include('PassingBarang.urls'), name= 'PassingBarang')
]

kenalan/urls.py
"""SSO UI urls module."""
from django.urls import path

from . import views

app_name = 'kenalan'
urlpatterns = [
    path('', views.index, name='index'),
    path('pertemuan/', views.daftar_pertemuan, name='daftar_pertemuan'),
    path('tambah/', views.tambah_pertemuan, name='tambah_pertemuan'),
    path('toggle_hadir/', views.toggle_hadir, name='toggle_hadir'),
    path('hapus/<int:id>/', views.hapus_pertemuan, name='hapus_pertemuan'),
    path('detail/<int:id>/', views.detail_pertemuan, name='detail_pertemuan'),
    path('komentar/<int:id>/', views.tambah_komentar, name='tambah_komentar'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kirim_pesan/', views.kirim_pesan, name='kirim_pesan')
]

tukerjakun/urls.py
from django.urls import path

from . import views

app_name = 'tukerjakun'
urlpatterns = [
    path('', views.get_formulir, name='index'),
    path('formulir/', views.get_formulir, name='tuker'),
    path('get_hasil_formulir/', views.get_hasil_formulir, name='tukerjakun'),
]

main/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.db import models
from sso_ui.models import Profile

# Create your models here.
class Pesan(models.Model):
    content = models.CharField(max_length=100)
    author = models.ForeignKey(Profile, related_name="author", on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm, TextInput
from .models import *

class PesanForm(ModelForm):
    class Meta:
        model = Pesan
        fields = '__all__'

        labels = {
            'content': ''
        }

        widgets = {
            'content': TextInput(attrs={
                'placeholder': 'Kirim pesan juga yuk...'
            })
        }
    

main/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Pesan
from .forms import PesanForm
from kenalan.models import Pertemuan
from PassingBarang.models import Barang
from tukerjakun.models import Tukaran

import copy, urllib, random, json, datetime, pytz, random

colors = ["red", "orange", "yellow", "green", "blue", "purple", "violet"]
emoji = ['😀', '😅', '🤭', '🤟', '🤣', '🙃', '😉', '😛', '🍀', '🥰', '🤪', '👽', '👻', '👀']

original = {
    "description" : "UImate",
    "title" : "UImate",
    "need_login" : False
}

def getNewestPertemuan():
    today_date = datetime.datetime.now(pytz.utc)
    pertemuans = Pertemuan.objects.order_by('waktu_mulai')
    
    newest_pertemuan = []
    for pertemuan in pertemuans:
        if pertemuan.waktu_mulai > today_date:
            newest_pertemuan.append(pertemuan)

    newest_pertemuan = newest_pertemuan[:min(7, len(newest_pertemuan))]
    return newest_pertemuan if newest_pertemuan else None

def getBarangWarisan():
    barang_warisan = list(Barang.objects.all())

    daftar_barang_pilihan = list()
    while (len(daftar_barang_pilihan) < 7) and (len(barang_warisan) > 0):
        barang_pilihan = random.choice(barang_warisan)
        daftar_barang_pilihan.append(barang_pilihan)
        barang_warisan.remove(barang_pilihan)

    return daftar_barang_pilihan

def getJakun():
    daftar_jakun = list(Tukaran.objects.all())

    daftar_jakun_pilihan = list()
    while (len(daftar_jakun_pilihan) < 7) and (len(daftar_jakun) > 0):
        jakun_pilihan = random.choice(daftar_jakun)
        daftar_jakun_pilihan.append(jakun_pilihan)
        daftar_jakun.remove(jakun_pilihan)

    return daftar_jakun_pilihan

def getDataCovid():
    with urllib.request.urlopen("https://data.covid19.go.id/public/api/update.json") as url:
        data = json.loads(url.read().decode())
    return data["update"]["total"]

def home(request):
    context = copy.copy(original)
    context['forms'] = PesanForm(request.POST or None)
    context['random_pesan'] = random.choice(Pesan.objects.all()) if Pesan.objects.all() else None
    context['newest_pertemuans'] = getNewestPertemuan()
    context['barang_pilihan'] = getBarangWarisan()
    context['daftar_jakun'] = getJakun()
    context['data_covid'] = getDataCovid()
    context["random_emoji"] = random.choice(emoji)
    return render(request, 'main/home.html', context)

def kirim_pesan(request):
    context = copy.copy(original)
    form = PesanForm(request.POST or None)
    if request.user.is_authenticated:
        if form.is_valid():
            form.save()
            messages.success(request, 'Pesan berhasil dikirim')
            return redirect('main:home')
        else:
            messages.error(request, 'Pesanmu terlalu panjang')
            return redirect('main:home')
    else:
        return redirect('sso_ui:login')
    

main/templates/main/home.html
{% extends 'base.html' %}


{% load static %}
{% load crispy_forms_tags %}


{% block cdnscript %}
<!-- Slick Carousel -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
  integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
  crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css"
  integrity="sha512-wR4oNhLBHf7smjy0K4oqzdWumd+r5/+6QO/vDda76MW5iug4PT7v86FoEkySIJft3XA0Ae6axhIvHrqwm793Nw=="
  crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
  integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
  crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
{% endblock %}


{% block style %}
<link href="{% static 'css/carousel.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}


{% block content %}
<div class="section-container">
  <!-- Homepage header -->
  <div class="container-fluid padding pl-5 pr-5">
    <div class="row text-center m-3">
      <div class="animate__animated animate__swing dark-text col-12">
        <h1 class="home-header semi-bold-font">{{random_emoji}} Selamat Datang {{random_emoji}}</h1>
        <h1 class="home-header semi-bold-font">
          {% if user.is_authenticated %}{% if user.get_full_name %}{{ user.get_full_name }}!{% else %}Pengguna
          Misterius!{% endif %}{% else %}Pahlawan Muda!{% endif %}
        </h1>
      </div>
    </div>
  </div>

  <!-- Random message -->
  <div class="container-fluid padding pl-5 pr-5">
    <div class="row text-center m-3">
      <div class="animate__animated animate__pulse random-color col-12">
        <p class="random-message">"{% if random_pesan %}{{ random_pesan.content }}{% else %}Bukan mager, tapi lagi <i>Power Saving Mode</i> ⚡{% endif %}"</p>      <b class="random-message">{% if random_pesan %}{{random_pesan.author}}{% else %}Rumput yang Bergoyang 🌿{% endif %}</b>
      </div>
    </div>
  </div>

  <!-- Message sender -->
  <div class="container-fluid padding pl-5 pr-5">
    <form action="{% url 'main:kirim_pesan' %}" method="POST"> {% csrf_token %}
      <div class="row center m-3">
        <div class="col-md-10 col-sm-12">
          {{ forms.content|as_crispy_field }}
        </div>
        <div class="col-md-2 col-sm-12">
          <button class="btn btn-success light-text send-button" type="submit">Kirim <i class="fa fa-arrow-circle-right"></i></button>
        </div>
        <input type="hidden" name="author" value="{{ user.id }}">
      </div>
    </form>
  </div>

  <!-- Message prompt -->
  {% include 'messages.html' %}

  <!-- COVID-19 updates -->
  <div class="container-fluid padding pl-5 pr-5 pt-1">
    <div class="dark-text row m-3">
      <h2 class="section-header semi-bold-font">Kondisi terkini COVID-19 di Indonesia...</h2>
    </div>

    <div class="row center padding dark-text m-3">
      <!-- Terkonfirmasi -->
      <div class="flex col-md-3 col-sm-6 col-xs-12 p-2">
        <div class="card covid-card large-hover blue text-center">
          <div class="card-body">
            <i class="case-icon icon fa fa-ambulance"></i>
            <p class="case-type">Terkonfirmasi</p>
            <p class="case-count">{{ data_covid.jumlah_positif }}</p>
          </div>
        </div>
      </div>

      <!-- Dirawat -->
      <div class="flex col-md-3 col-sm-6 col-xs-12 p-2">
        <div class="card covid-card large-hover yellow text-center">
          <div class="card-body">
            <i class="case-icon icon fa fa-hospital"></i>
            <p class="case-type">Dirawat</p>
            <p class="case-count">{{ data_covid.jumlah_dirawat }}</p>
          </div>
        </div>
      </div>

      <!-- Sembuh -->
      <div class="flex col-md-3 col-sm-6 col-xs-12 p-2">
        <div class="card covid-card large-hover green text-center">
          <div class="card-body">
            <i class="case-icon icon fa fa-hand-holding-medical"></i>
            <p class="case-type">Sembuh</p>
            <p class="case-count">{{ data_covid.jumlah_sembuh }}</p>
          </div>
        </div>
      </div>

      <!-- Meninggal -->
      <div class="flex col-md-3 col-sm-6 col-xs-12 p-2">
        <div class="card covid-card large-hover red text-center">
          <div class="card-body">
            <i class="case-icon icon fa fa-pray"></i>
            <p class="case-type">Meninggal</p>
            <p class="case-count">{{ data_covid.jumlah_meninggal }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Upcoming events -->
  {% if newest_pertemuans %}
  <div class="container-fluid padding pl-5 pr-5 pt-2">
    <div class="row m-3">
      <h2 class="section-header bold-font">Sebentar lagi akan ada acara ini...</h2>
    </div>

    <div class="row center padding dark-text m-3">
      <div class="col-12 slick-carousel">
        {% for pertemuan in newest_pertemuans %}
        <div class="flex event-card p-2">
          <a class="event-card-link" href="{% url 'kenalan:detail_pertemuan' id=pertemuan.id %}">
            <div class="card event-card large-hover rainbow-card">
              <div class="card-body event-card-content">
                <h4 class="ellipsis-overflow">📢 {{ pertemuan.nama }}</h4>
                <p class="ellipsis-overflow">👑 oleh {{ pertemuan.pembuat|default:" " }}</p>
                <p class="ellipsis-overflow">📆 {{ pertemuan.waktu_mulai|date:'l, d E Y' }}</p>
                <p class="ellipsis-overflow">⏰ Pukul {{ pertemuan.waktu_mulai|date:'H:i' }}</p>
                <p class="ellipsis-overflow">⏲️ {{ pertemuan.durasi }}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
        <div class="flex event-card p-2">
          <a class="event-card-link" href="{% url 'kenalan:daftar_pertemuan' %}">
            <div class="card last-event-card">
              <div class="card-body">
                <h4>Lihat semuanya</h4>
                <p>Klik di sini <i class="fa fa-arrow-circle-right"></i></p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Barang Pilihan -->
  {% if barang_pilihan %}
  <div class="container-fluid padding pl-5 pr-5">
    <div class="row m-3">
      <h2 class="section-header bold-font">Ambil sebelum keduluan...</h2>
    </div>

    <div class="row center padding dark-text m-3">
      <div class="col-12 slick-carousel">
        {% for barang in barang_pilihan %}
        <div class="flex event-card p-2">
          <a class="event-card-link" href="{% url 'PassingBarang:detil' id_number=barang.id%}">
            <div class="card event-card large-hover rainbow-card">
              <div class="card-body event-card-content">
                <h4 class="ellipsis-overflow">📦 {{ barang.nama }}</h4>
                <p class="ellipsis-overflow">👑 milik {{ barang.pemilik }}</p>
                <p class="ellipsis-overflow">💵 {{ barang.harga }}</p>
                <p class="ellipsis-overflow">📌 {{ barang.lokasi }}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
        <div class="flex event-card p-2">
          <a class="event-card-link" href="{% url 'PassingBarang:index' %}">
            <div class="card last-event-card">
              <div class="card-body">
                <h4>Lihat semuanya</h4>
                <p>Klik di sini <i class="fa fa-arrow-circle-right"></i></p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Carousel Jakun -->
  {% if daftar_jakun %}
  <div class="container-fluid padding pl-5 pr-5">
    <div class="row m-3">
      <h2 class="section-header bold-font">Jakun kegedean? Kekecilan? Tenang...</h2>
    </div>

    <div class="row center padding dark-text m-3">
      <div class="col-12 slick-carousel">
        {% for jakun in daftar_jakun %}
        <div class="flex event-card p-2">
          <a class="event-card-link disabled-card">
            <div class="card event-card large-hover rainbow-card">
              <div class="card-body event-card-content">
                <h4 class="ellipsis-overflow">{{ jakun.makara }}</h4>
                <p class="ellipsis-overflow">👑 milik {{ jakun.nama }}</p>
                <p class="ellipsis-overflow">📏 ukuran {{ jakun.ukuran }}</p>
                <p class="ellipsis-overflow">☎️ {{ jakun.kontak }}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
        <div class="flex event-card p-2">
          <a class="event-card-link" href="{% url 'tukerjakun:tukerjakun' %}">
            <div class="card last-event-card">
              <div class="card-body">
                <h4>Lihat semuanya</h4>
                <p>Klik di sini <i class="fa fa-arrow-circle-right"></i></p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock content %}

{% block userscript %}
<script src="{% static 'scripts/rainbowcard.js' %}"></script>
<script src="{% static 'scripts/slick.js' %}"></script>
<script src="{% static 'scripts/randomcolor.js' %}"></script>
{% endblock userscript %}